### ISSUE TITLE
Sublime plugin: AutoBackups support

### ISSUE THREAD

**Issue by jtojnar** [GhostText/GhostText#102]
I just lost some text I was writing since yesterday. Could you associate the buffer with a file so that [AutoBackups](https://github.com/akalongman/sublimetext-autobackups) can track it?

**Comment by bfred-it** [comment]
I'm not familiar with how ST handles that, is it a quick change that you can make via PR?

**Comment by bfred-it** [comment]
Or perhaps you could make this optional: https://github.com/GhostText/GhostText-for-SublimeText/commit/6ac2b75bf73767d9a59e7dbfb66c838489f78645

**Comment by jtojnar** [comment]
I am not that familiar with sublime plugin development but AutoBackups seem to [check for filename](https://github.com/akalongman/sublimetext-autobackups/blob/f57b7a230ee8389a0b87d4244d1213fdd6f8347f/AutoBackups.py#L126) so not setting scratch probably won’t be enough.

**Comment by bfred-it** [comment]
I don't think this can ever work with AutoBackups then, even if the filename was set, it's not really saved anywhere. Scratch is what makes ST let you close the window without saving and eventually I think that's what would benefit you.
