### ISSUE TITLE
Firefox Ace Editor | Error: Permission denied to access property "text"

### ISSUE THREAD

**Issue by coltoneakins** [GhostText/GhostText#104]
For textareas using [Ace](https://ace.c9.io/) on Firefox, text is only sent one-way from the browser to the external text editor. Text sent in the reverse direction is not written to the Ace editor. The browser console lists the following error:

> Error: Permission denied to access property "text"

which is listed for every text character the user had typed in the external text editor. In the following examples, the phrase '_test_' was typed on the external text editor for a [HasteBin](https://hastebin.com/) textarea versus an Ace editor textarea. 

HasteBin:

![hatebinfirefoxghosttext](https://user-images.githubusercontent.com/16803020/31313912-f7297550-abb6-11e7-8389-64fbe7363b9b.gif)

Ace:

![acefirefoxghosttext](https://user-images.githubusercontent.com/16803020/31313916-05075926-abb7-11e7-8199-abf4293caeab.gif)

The issue exists in the Firefox release (not using the WE version), Firefox Developer Edition (using the WE version), and Firefox Nightly (using the WE version). Issue does not appear on Google Chrome. Issue was also tested using Atom and Emacs as the external text editor. The issue persists on Firefox regardless of the editor used in my tests.

Notice that the warning does not appear in the first example using the HasteBin textarea.

**Comment by coltoneakins** [comment]
The error corresponds to the `<script>` tags injected by the extension with id:  `#ghost-text-injected-script-ace_editor_demo` and `#ghost-text-injected-script-embedded_ace_code` (two different, injected `<script>` tags). Specifically, it refers to line 17:


>                     ghostTextAceDiv.addEventListener("GhostTextServerInput", function (e) {
>                         console.log('test');
>                         ghostTextAceEditorSession.setValue(e.detail.text);
>                     });

**Comment by coltoneakins** [comment]
It seems that the `detail` property became _inaccessible_ when it was dispatched in the `input-area.js` (where the CustomEvent was defined) to this injected JS code.

**Comment by bfred-it** [comment]
Thank you for your report! Could you look into fixing the issue?

**Comment by coltoneakins** [comment]
I changed the `CustomEventInit` dictionary--the 'detail'--(found [here](https://github.com/GhostText/GhostText/blob/25ab62513d1980212d6ed89e24efcab1612e66f9/browser/scripts/InputArea/JSCodeEditor.ts#L154)) from:

`
            this.currentText = text;
            var details = {detail: {text: this.currentText}};
            var gtServerInputEvent = <Event>StandardsCustomEvent.get('GhostTextServerInput', details);
this.jsCodeEditorDiv.dispatchEvent(gtServerInputEvent);
`

to:

'
            this.currentText = text;
            var details = {detail: this.currentText};
            var gtServerInputEvent = <Event>StandardsCustomEvent.get('GhostTextServerInput', details);
this.jsCodeEditorDiv.dispatchEvent(gtServerInputEvent);
'
And, I changed the listener in the injected script (found [here](https://github.com/GhostText/GhostText/blob/25ab62513d1980212d6ed89e24efcab1612e66f9/browser/scripts/InputArea/AceCodeEditor.ts#L30)) from:

`
                ghostTextAceDiv.addEventListener("GhostTextServerInput", function (e: any) {
                    ghostTextAceEditorSession.setValue(e.detail.text);
});
`
to:
`
                ghostTextAceDiv.addEventListener("GhostTextServerInput", function (e: any) {
                    ghostTextAceEditorSession.setValue(e.detail);
});
`

This fixed the issue. GhostText is now working for Ace textareas on Firefox. However, this isn't really _the fix_ as I am not sure what would cause the permission to access `text` to be denied in the first place. A `CustomEvent` dispatched to the injected script with the  `CustomEventInit` dictionary should be able to share its detail object. My guess is that it could be something related to the CSP for the page/extension. I am still investigating before I submit any sort of pull request.

**Comment by danihodovic** [comment]
@coltoneakins did you manage to fix the issue in the end? Would you be willing to supply a pull-request?

**Comment by indigoviolet** [comment]
any updates on this? I now see this error with Firefox latest/Jupyter lab.

**Comment by ian-h-chamberlain** [comment]
Seems to be the same issue on https://www.shadertoy.com/new

**Comment by fregante** [comment]
Can you test the new version? It hasn't been published to the stores yet: https://github.com/GhostText/GhostText/issues/172

This should be fixed now

**Comment by coltoneakins** [comment]
This issue is fixed in the newer rewrite of GhostText.

See: https://github.com/GhostText/GhostText/issues/172

And the report where I test this issue with the new rewrite: https://github.com/GhostText/GhostText/issues/172#issuecomment-749952855
