### ISSUE TITLE
"Disconnected!" when Changing Language Mode [VS Code]

### ISSUE THREAD

**Issue by timharris777** [GhostText/GhostText#106]
When using ghost with VS Code if I try and change the Language Mode (syntax) after selecting the new language mode I get a message saying "Disconnected \n Report Issues | Leave Review". This pretty much renders the editor useless as the whole reason I want to use VS Code is to benefit from the different language modes.

**Comment by bfred-it** [comment]
The VS Code extension is from a third party, there's an issue open there: https://github.com/jtokoph/ghosttext-vscode/issues/1
