### ISSUE TITLE
Graceful failure if a supported editor isn't running

### ISSUE THREAD

**Issue by mavit** [GhostText/GhostText#111]
Things fail in a confusing way if a supported editor is not already running when trying to use GhostText.

Steps to reproduce:

1. Install Firefox addon from https://addons.mozilla.org/en-US/firefox/addon/ghosttext/
1. Navigate to a webpage containing a text box.
1. Click the GhostText button in the Firefox toolbar.  The text box turns blue.
1. Install atomic-chrome package for Emacs.
1. Start atomic-chrome with `(atomic-chrome-start-server)`.
1. Try clicking the GhostText button in Firefox again.
1. Observe that a message pops up in the browser saying "Connected", the GhostText icon has a green "ON" label, and a new buffer opens in the editor.  Hurrah!
1. Try to edit text in the browser.  Observe that it is transferred to the editor.  Spendid!
1. Try to edit text the editor.  Observe that it is **not** transferred to the browser.  Oh.

**Comment by bfred-it** [comment]
The order is wrong, you should first start the server, then click on the button **once**.

**Comment by mavit** [comment]
Sure, I figured that out in the end, but it would be better not to be able to get into that situation.  It's inconsistent that you can toggle syncing on an off by clicking the icon, but only if syncing is working properly.

**Comment by fregante** [comment]
This has been fixed in v21.

![gif](https://user-images.githubusercontent.com/1402241/106236635-e8aaf600-61c2-11eb-9512-8fd43425e2c8.gif)
