### ISSUE TITLE
Change keybinding on Firefox?

### ISSUE THREAD

**Issue by dudelson** [GhostText/GhostText#113]
The README says that the key binding can be changed, but this appears to be chrome-specific advice only. On firefox, Ctrl-Shift-h opens the history, and Ctrl-Shift-k opens the browser console, so these keys appear to be interpreted by firefox instead of being passed to GhostText. I would like to change the keybinding, but there is no option in the GhostText extension preferences that allows me to do this.

**Comment by KatieK2** [comment]
Please do create some way to change the key binding for Firefox. When I use "Control Shift k" in Firefox, I expect to get the browser dev tools with focus on the Console tab. However, with GhostText enabled, I instead get a red error box saying "No textarea elements on this page". Inspecting this element in the DOM reveals that it has these classes: `ghost-text-message ghost-text-message-error`. GhostText is interfering with Firefox's (Firefox Quantum v57.0.2 (64-bit) in Windows 10) default keyboard commands.

**Comment by duncan-bayne** [comment]
Would you accept a PR to fix this?  It's the only pain point I'm experiencing with this otherwise wonderful tool, which has made Firefox 57 bearable in the absence of It's All Text.

**Comment by bfred-it** [comment]
I see a lot of Firefox users coming from the old It's All Text. Sorry for the neglect!

Indeed Firefox does not yet offer a UI to change the key bindings like Chrome does, so for now I disabled the shortcuts there.

I disabled the keyboard shortcuts in Firefox until they provide the UI. Keep an eye on this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by dudelson** [comment]
Will do. Thanks!

**Comment by Stvad** [comment]
It'd be great to have at least some shortcut by default (non conflicting one), though

**Comment by WJCFerguson** [comment]
I'm puzzled why this is closed, given that it hasn't got a shortcut (no?) and is pending a Firefox fix that hasn't landed yet (?).

**Comment by bfred-it** [comment]
> **I disabled the keyboard shortcuts in Firefox until they provide the UI**

**Comment by WJCFerguson** [comment]
Ok, in that case I submitted issue #147 to request a keyboard shortcut.

Thank you for your efforts!
