### ISSUE TITLE
Option to set the default type/language mode

### ISSUE THREAD

**Issue by iherman** [GhostText/GhostText#118]
I use GT mostly with GitHub (for comments) and Visual Studio Code as my editor. When using GT the text is set to text mode with a temporary file with .txt suffix. However, if I change it to markdown mode in Visual Studio Code, the file name (extension) changes, and GT looses connection.

It would be good to have an option in GT to change the default suffix for the file. Even better, if I had a choice when I invoke the editor to choose the file type (you can do it with ItsOnlyText extension in the old Firefox versions).

(Using Firefox 57 on OS X)

**Comment by bfred-it** [comment]
GT-VScode is a third party plugin so refer to its own repo for the bug you’re describing. GT-SublimeText already defaults to Markdown and supports domain-matching for languages.
