### ISSUE TITLE
Use file names corresponding to webpages URLs

### ISSUE THREAD

**Issue by doronbehar** [GhostText/GhostText#119]
Back in Firefox version <57, when we used [itsalltext](https://github.com/docwhat/itsalltext), the add-on opened a `.txt` file and the name of the file corresponded to the URL of the webpage.
For example, for the webpage I'm editing right now, the file name would be something like `github.com_GhostText_GhostText_issues_new_jakd1312.txt` (including the random characters). In addition, I told itsalltext to open a terminal emulator with Vim and the said file. Next, in [my Vim configuration](https://github.com/doronbehar/.config_nvim), I created a new file type for [itsalltext](https://github.com/doronbehar/.config_nvim/blob/master/ftplugin/itsalltext.vim) and I [detect(ed)](https://github.com/doronbehar/.config_nvim/blob/master/filetype.vim#L3) the files created by the add-on and set custom settings for files from certain websites.

For example, it enables me to automatically have markdown syntax in my text editor for text areas in webpages like [stackexchange](https://stackexchange.com)'s and [stackoverflow.com](https://stackoverflow.com)'s, or `mediawiki` syntax in Wikipedia-like pages.

For those who don't know Vim-Lang, I use regular expressions to set custom editor settings for files whose paths'/names' match the expressions.
I don't how many of you people here use Vim/Neovim but it is one of it's best feature and I really miss having it.

I hope it's not that hard to implement it as well.

Thanks for a wonderful application.

**Comment by bfred-it** [comment]
This is part of #95

Currently the URL is already sent to the editor, however I doubt it’s actually implemented by any editor plugin except the official one (sublime)

Additionally I’m not sure of what you’re referring to with terminal emulation but I think that’s not gonna be possible with the current extension framework.
