### ISSUE TITLE
Define a default editor

### ISSUE THREAD

**Issue by dertuxmalwieder** [GhostText/GhostText#123]
Some people like me have different text editors installed. There should be a way to define which one is the main editor. (I have no idea what happens when e.g. Sublime Text and Emacs are both attached to a text box...?)

It's All Text could start the preferred editor from within Firefox. Would that be a possibility too?

**Comment by bfred-it** [comment]
GhostText just open whatever editor is listening on port 4001 (customizable)

If you don’t want emacs to connect, then don’t install GhostText in it, or disable the plugin in it, or just change its GhostText server port to 4002.
