### ISSUE TITLE
"slugify() got unexpected keyword argument"

### ISSUE THREAD

**Issue by zwkrt** [GhostText/GhostText#125]
When attempting to install vim-ghost on my Mac install of neovim, I get this error at the time that my browser extension attempts to connect to the server. The server seems to start correctly.

Server Environment: 
Mac OSX 10.13.2
neovim v0.2.1
python 3.6

Browser:
firefox dev edition 58.0b11

python packages installed:
neovim==0.2.0
SimpleWebSocketServer==0.1.0
slugify==0.0.1
unicode-slugify==0.1.3

**Comment by Natureshadow** [comment]
Sounds like a vim-ghost issue rather than one in GhostText.

**Comment by bfred-it** [comment]
That’s correct, can you open an issue in the GhostText for vim repo? This repo is just for the browser extensions and sublime/atom

**Comment by zwkrt** [comment]
sorry about that!

**Comment by mcepl** [comment]
The bug has been filed by @zwkrt as raghur/vim-ghost#6.
