### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by gynet** [GhostText/GhostText#128]
It's not working with windows 10, the editor start flick

**Comment by gynet** [comment]
Using ghost text with chrome and vs code under windows 10. No such issue with Mac

**Comment by pabli24** [comment]
I also have problems with ghosttext in visual studio code on windows 10. 
In sublime text works great.

**Comment by bfred-it** [comment]
It sounds like this is an issue with the visual studio plugin. Please open an issue in their repo
