### ISSUE TITLE
Firefox/ST3 - Does not work with https://asciidoclive.com

### ISSUE THREAD

**Issue by raghur** [GhostText/GhostText#129]
# Setup

Browser: Firefox 60 (Developer edition)
Editor: Sublime text 3

# Description
Does not work with https://asciidoclive.com/edit/scratch/1. There are permission errors logged in console. 
Chromium with sublime text on the same url works though.
1. Clicking ghost text icon opens st3
2. editing text on st3 does not update the text in the browser.

![image](https://user-images.githubusercontent.com/516267/36015932-acf3505e-0d96-11e8-938e-0b0b98b77b27.png)

**Comment by bfred-it** [comment]
Thanks for the report! Same as https://github.com/GhostText/GhostText/issues/104
