### ISSUE TITLE
ghostText doesn't work with tiddlywiki

### ISSUE THREAD

**Issue by pekcheey** [GhostText/GhostText#137]
# Setup

Browser: Chrome
Editor: macvim

# Description

clicking on the ghosttext icon to launch ghosttext in tiddlywiki doesn't seems to have any effect.

**Comment by bfred-it** [comment]
Have you tried in Sublime Text?

**Comment by pekcheey** [comment]
Sorry for the late update. I tried. using Sublime but it doesn't work as well for tiddlywiki. 
I think the chrome extension wasn't detecting the text field in the tiddler. 

btw, I'm using the noteself variant of tiddlywiki 5 it just add syncing for the tiddlers to a couchdb instance.

**Comment by fregante** [comment]
Can you test the new version? It hasn't been published to the stores yet: https://github.com/GhostText/GhostText/issues/172
