### ISSUE TITLE
[Feature Request] Update file extension or editor extension to allow automatic Markdown preview

### ISSUE THREAD

**Issue by Enteleform** [GhostText/GhostText#139]
VSCode's [**Markdown All in One**](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension has a 
```
"markdown.extension.preview.autoShowPreviewToSide"
```
setting that automatically opens markdown file previews to the side.
&nbsp;  

EG:

![code_2018-07-22_02-38-04](https://user-images.githubusercontent.com/10906415/43043039-4d728950-8d58-11e8-9e50-70423014900d.png)

&nbsp;

Two implementations that might allow GhostText to take advantage of this functionality:

- change the `.tmp` extension to `tmp.md`

- have  `VSCode` & other editors' GhostText extension automatically set the langage mode to Markdown

**Comment by bfred-it** [comment]
Same as https://github.com/GhostText/GhostText/issues/65

You can ask on the GT VS Code repo to use the correct extension
