### ISSUE TITLE
tagged releases

### ISSUE THREAD

**Issue by anarcat** [GhostText/GhostText#142]
It would be great if the GhostText project would tag releases in the git repository, preferably following the [semantic versioning](https://semver.org/) standard. This would make it easier for downstream distributions to follow your work and package the extension for our users.

**Comment by bfred-it** [comment]
Semantic version doesn't apply to extensions. The browser download the latest version, that's it. Every version is automatically deployed. The last commit of this project was 6 months ago so I don't see the problem.

**Comment by bfred-it** [comment]
If you can figure out how to set up Travis to create a nightly release (if there are any changes) then no problem.

In Refined GitHub we set up a daily cron-job + a condition that checks if any commits were created in the last day:

https://github.com/sindresorhus/refined-github/blob/0903681cc9935f2299806acce531e0bf830bf8e3/.travis.yml#L18

https://github.com/sindresorhus/refined-github/blob/0903681cc9935f2299806acce531e0bf830bf8e3/package.json#L14

Either way the version wouldn't be "semantic"
