### ISSUE TITLE
vim plugin support in https://github.com/pandysong/ghost-text.vim

### ISSUE THREAD

**Issue by pandysong** [GhostText/GhostText#143]
I have written a plugin in python3 and vim's channel feature. Please consider to add to the list in the front-page:

https://github.com/pandysong/ghost-text.vim

**Comment by bfred-it** [comment]
There’s already a vim script, does this differ?

**Comment by pandysong** [comment]
sure. PR created:
https://github.com/GhostText/GhostText/pull/144

**Comment by pandysong** [comment]
Thanks.
