### ISSUE TITLE
GhostText does not work sometimes depending on content of text box

### ISSUE THREAD

**Issue by joeaddison** [GhostText/GhostText#150]
# Setup

Browser: Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
Editor: Sublime text Version 3.1.1 Build 3176

# Description
Love Ghost Text!  I do have an issue where it will sometimes not work depending on the code that is in the text box.

When this happens, I get the following error briefly at the bottom of sublime:
Line 1, Column 1; ghostText - Invalid JSON:, Unterminated string starting at: line 1 column 9(char 8), Traceback(most recent call last)

Rename attached file to .html, and it will have a text box that does not work (for me at least).

[ghost.txt](https://github.com/GhostText/GhostText/files/2715713/ghost.txt)

Thanks!

**Comment by fregante** [comment]
Can you test the new version? It hasn't been published to the stores yet: https://github.com/GhostText/GhostText/issues/172

**Comment by fregante** [comment]
It seems that Sublime Text just goes in a loop when receiving data and it spikes to 100% CPU usage. I'm not sure if this is related to #180 but it needs to be fixed regardless.

Unfortunately the Python developer is gone so the Sublime Text extension won't be fixed unless someone steps up 😕

**Comment by fregante** [comment]
With a minor modification in the browser extension, the CPU spike and disconnection doesn't seem to happen anymore on the attached document and performance is generally much better with large documents. I hope it won't cause issues.
