### ISSUE TITLE
Problem with two-way sync on Overleaf in Firefox (works flawlessly in Chrome)

### ISSUE THREAD

**Issue by macthecadillac** [GhostText/GhostText#154]
# Setup

Browser: Firefox
Editor: Neovim

# Description
On Overleaf, the text in the editing area in source mode (an editing mode on Overleaf, you basically edit the LaTeX source code directly without any fancy stuff) syncs only one-way to my editor but not the other way around. The issue doesn't exist in Chrome.

# Reproduction
Head over to Overleaf, open an account, open a new document, and activate GhostText in the editing area with Firefox. Repeat the same steps with Chrome (perhaps without opening another account unless you want to for unspecified reasons) and compare.

**Comment by Escapingbug** [comment]
Any updates on this? Run into the same issue here.

**Comment by doronbehar** [comment]
The same issue here with https://www.swiftlatex.com

**Comment by skeleten** [comment]
I'm experiencing the same issue, but using Emacs with the `atomic-chrome` package.
Firefox version is 77.0.1

**Comment by fregante** [comment]
Can you test the new version? It hasn't been published to the stores yet: https://github.com/GhostText/GhostText/issues/172

**Comment by fregante** [comment]
This works correctly in the latest version (not yet published to the stores)

Sorry for the long wait for an answer!
