### ISSUE TITLE
Not working with repl.it

### ISSUE THREAD

**Issue by mossr** [GhostText/GhostText#155]
# Setup

Browser: Google Chrome Version 74.0.3729.169
Editor: Sublime Text 3 (3207)

# Description
GhostText does not work with the [repl.it](https://repl.it/) website. After clicking the GhostText Chrome extension button, the drop down appears as normal:

> There are multiple textarea elements on this page. 
> Click on the one you want to use.

I select the left-hand textbox and most of the code appears within Sublime Text, _**but nothing is updated when I change the text within Sublime.**_ Surprisingly, you can edit the [repl.it](https://repl.it/) textbox and the changes appear within the Sublime tab (but not the other way around).

[Repl.it](https://repl.it/) is very useful for online programming with various languages (I use it primarily as a C++ REPL).

**Comment by wizzup** [comment]
`repl.it` also use `monaco`

This issue should be closed in favor of #140
