### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by mcdviii** [GhostText/GhostText#157]
This appears to be no longer supported on Firefox. Is anyone aware of any good (working) alternatives?

Thanks.

**Comment by fregante** [comment]
I’m using it on Firefox, what do you mean it’s not supported

**Comment by mcdviii** [comment]
Very odd. I apologize for jumping the gun with a garbage bug report. It appears to be working again, somehow.
I had an issue with the GhostText icon not showing up in the browser toolbar. It would hold a space, but the visual icon would not show up & the button was un-clickable. I wagered that the project was no longer being maintained. I'll open another issue with helpful details if the problem persists.
