### ISSUE TITLE
Doesn't work with google docs

### ISSUE THREAD

**Issue by Liverm0r** [GhostText/GhostText#162]
# Setup

Browser: chrome
Editor: vim, [this plugin](1)
OS: linux manjaro

# Description

My setup works in stackoverflow, leetcode and github.
Can't make it work with google docs.

Chrome extension notifies me that everything is connected, but when I switch to vim and type, text doesn't appear in google-docs.

I tried adding comments in 'suggesting' mode, and it doesn't work either.

[1]: [https://github.com/pandysong/ghost-text.vim]

**Comment by fregante** [comment]
There’s no way this will ever work on Google Docs, it’s too complex. I don’t think it’s a good idea to code in Google Docs anyway

**Comment by Liverm0r** [comment]
I agree, some interviewers don't don't :)
