### ISSUE TITLE
Question: on information set to the editor

### ISSUE THREAD

**Issue by truesilver92** [GhostText/GhostText#165]
Does GhostText send metadata information to the editor such as when
linewraps occur, or how many columns the field is?

**Comment by fregante** [comment]
No, GitHub only transfers the text and domain

**Comment by truesilver92** [comment]
@fregante GhostText only transfers the text and domain?

**Comment by fregante** [comment]
Yes, sorry 😅

**Comment by truesilver92** [comment]
No problem. Thank you for the work you have put into this project.
