### ISSUE TITLE
Right-click menu option to edit a text box using GhostText

### ISSUE THREAD

**Issue by JosephKiranBabu** [GhostText/GhostText#166]
This is the current flow of editing a text box in GhostText

1. Go to the browser bar and click on the extension icon.
2. (if there are multiple text boxes) select the text box you want to edit.

This can be reduced to a single step by adding a right-click option to select a text box to edit.
For power users, a configurable shortcut on the text box like Alt+Enter would be more useful.

**Comment by fregante** [comment]
You can already customize the shortcut https://github.com/GhostText/GhostText#keyboard-shortcuts

> This can be reduced to a single step by adding a right-click option to select a text box to edit.

That's still two steps:
- right click
- click GhostText


Anyway, GhostText will automatically use the focused field, if found, making it one-click.

The number of clicks literally cannot be reduced any further.

**Comment by JosephKiranBabu** [comment]
Maybe I didn't describe the problem very well. 

As I'm writing in this text box now, it's inconvenient to go to the browser bar, find the GhostText icon, click it and come back to the text box. So, I found that I'm not using GhostText as much as I was using the "Edit with Emacs" addon which had an Alt+Enter shortcut. Even if I didn't remember the shortcut, the add-on could be triggered from the right-click option. I'm missing both in GhostText.

The convenience of having your text appear instantly in the browser is not even reached because of this starting trouble.

--
Not written using GhostText

**Comment by fregante** [comment]
> Even if I didn't remember the shortcut, the add-on could be triggered from the right-click option.

GhostText _can_ be triggered with the shortcut too, and it's customizable.

**Comment by JosephKiranBabu** [comment]
Thanks. The shortcut is good enough for my use case.
