### ISSUE TITLE
Leave a review links to chrome store on Firefox

### ISSUE THREAD

**Issue by andinus** [GhostText/GhostText#167]
# Setup

Browser: Mozilla Firefox 68.5.0esr
Editor: GNU Emacs 26.3

# Description

GhostText shows "Leave review" link after closing the editor, it links to the chrome store. On Firefox it should link to [AMO](https://addons.mozilla.org).

**Comment by fregante** [comment]
Thanks! The link has been removed in the newest version.

You can test it here before I publish it: https://github.com/GhostText/GhostText/issues/172
