### ISSUE TITLE
Feature Request - option to define a file extension instead of .tmp (to use markdown preview with .md files)

### ISSUE THREAD

**Issue by aisbergde** [GhostText/GhostText#168]
# Setup

Browser: Chrome
Editor:  Visual Studio Code

# Description

Visual Studio Code has some Markdown Features, there are plugins to preview markdown, I use the "Markdown All in One" plugin.

But the preview is shown only for files with the extension ".md"

When I use GhostText with the GhostText plugin then files with the extension ".tmp" are created and Markdown Preview will not work.

Is there a way to configure the file extension of the temp files which are used to connect the editor and the web? Or are there any ideas how to configure the "Markdown All in One" plugin to work with .tmp files?

**Comment by fregante** [comment]
This is something the VS Code plugin should handle
