### ISSUE TITLE
Firefox extension doesn't work with GitHub gist editor

### ISSUE THREAD

**Issue by jeremymeng** [GhostText/GhostText#170]
# Setup

Browser: Firefox 78.0.2
Editor: Emacs + atomic-chrome package

# Description

The Firefox extension doesn't work for GitHub gist editor.  The Chrome extension works as expected for GitHub gist editor.

After clicking on the text area, I am getting the following in the Emacs window

```
<div style="position: relative;"><div class="CodeMirror-gutter-wrapper" style="left: -53px;" contenteditable="false"><div class="CodeMirror-linenumber CodeMirror-gutter-elt" style="left: 0px; width: 21px;">1</div></div><pre class=" CodeMirror-line " role="presentation"><span role="presentation"><span cm-text="">​</span></span></pre></div>
```

![image](https://user-images.githubusercontent.com/7583839/87238421-355de980-c3b7-11ea-8657-19a3c7f59b5e.png)

for comparison, this shows same editor working for Chrome

![image](https://user-images.githubusercontent.com/7583839/87238476-af8e6e00-c3b7-11ea-95ef-a065866e4202.png)

**Comment by dyno** [comment]
i have the same problem with jupyterlab. chrome/vim works both way but vim => firefox is broken.

**Comment by fregante** [comment]
Can you test the new version? It hasn't been published to the stores yet: https://github.com/GhostText/GhostText/issues/172

**Comment by jeremymeng** [comment]
@fregante Same issue with 20.11.27
