### ISSUE TITLE
GhostText v21 (new update) doesn't reflect changes done on Vs Code

### ISSUE THREAD

**Issue by jeremiahlobo** [GhostText/GhostText#181]
# Setup

Browser: Chrome
Editor: Vs Code

# Description
GhostText connects to Vs Code editor however doesn't reflect the changes on the webpage's "textfield" after typed on Vs Code using the vscode extension

**Comment by fregante** [comment]
Can you try Sublime Text? It’s the only one I tried so far (and others have tried Vim as well)

**Comment by jeremiahlobo** [comment]
I will try sublime but we use other VS code extensions while coding and love to see it working again

**Comment by jeremiahlobo** [comment]
![image](https://user-images.githubusercontent.com/11907695/106188490-e1043680-615b-11eb-9c36-288f4cae6947.png)
 update - I tried to do the same with sublime text it does get the code on the text but the change from the code doesn't show up on the textfield

**Comment by fregante** [comment]
Are you working on a private site or can you share the URL?

Does it work here? https://ghosttext.github.io/GhostText/demo/

**Comment by jeremiahlobo** [comment]
Weirdly it works on the url you sent me, Sorry working on a private site. But We fixed it by revert this code and ablke to use it https://github.com/GhostText/GhostText/commit/faa5a8d8ea744907b1f968b915c34f30e1dd96a7

**Comment by fregante** [comment]
Thank you for identifying the issue!

Yeah I knew that code would cause trouble for some. On the demo page, the fields in the iframe don't work for example. I'll probably have to move that detection to the `background.js` script

**Comment by DevJHennessy** [comment]
Hey fregante,

I'm using Chrome and Sublime, and it's no longer working for me or my coworkers. The connection seems to be one way, where the edits made in the browser show up in Sublime, but any edits in Sublime do not translate to the browser. I tried it on your demo site with the same results. I'm getting this red pop-up that reads: "No Supported Elements Found!"

**Comment by fregante** [comment]
> but any edits in Sublime do not translate to the browser

Do you see any messages in the browser’s console?

> I tried it on your demo site with the same results. I'm getting this red pop-up that reads: "No Supported Elements Found!"

How's it possible that it doesn't work at all on that page? Can you see any errors on the console in this case as well?

**Comment by DevJHennessy** [comment]
Here's what I'm seeing in the console as well as on the demo page.
<img width="704" alt="20210128-GhostText-Demo-Page-Screenshot" src="https://user-images.githubusercontent.com/34386510/106196725-a2c04480-6166-11eb-9023-2357be6a5320.png">

<img width="783" alt="20210128-GhostText-Demo-Page-and-Console-Screenshot" src="https://user-images.githubusercontent.com/34386510/106196751-ace24300-6166-11eb-98b9-1bbc8331daa8.png">

<img width="288" alt="20210128-GhostText-Screenshot" src="https://user-images.githubusercontent.com/34386510/106196764-b075ca00-6166-11eb-8455-6df328c63f55.png">

The console is sometimes reporting that an update from the editor is being ignored, but I've closed it down and updated the extension and it shows the same error.

**Comment by fregante** [comment]
I'll release a new version without that piece of code within an hour

**Comment by DevJHennessy** [comment]
Okay, thank you very much!

**Comment by jeremiahlobo** [comment]
Thanks @fregante  and all you have done with ghost text, Closing this issue :)

**Comment by fregante** [comment]
I'll leave this open for a little bit longer so others can see if they have issues

**Comment by fregante** [comment]
v21.1.18 is live on Chrome.

**Comment by jeremiahlobo** [comment]
Thanks @fregante testing it in a min :)

**Comment by jeremiahlobo** [comment]
Tested and Works :) Thanks again

**Comment by DevJHennessy** [comment]
Thanks for the prompt update @fregante ! Glad it's working again!

**Comment by jeremiahlobo** [comment]
![image](https://user-images.githubusercontent.com/11907695/106340948-52251600-6250-11eb-9d5b-f2e77a586448.png)
Hey @fregante  just a short update after your push, been getting this console errors, not sure if it anything to be concerned about

**Comment by fregante** [comment]
That's because the VSCode extension doesn't send any selection, but it should: https://github.com/jtokoph/ghosttext-vscode/blob/1e460166558d0e53bf879f6c19d15cec320ac668/extension.js#L73

You can open an issue there.

**Comment by fregante** [comment]
Closing because Firefox will also get the latest bug-free version (whenever they get to approve it)
