### ISSUE TITLE
Multiple textareas

### ISSUE THREAD

**Issue by adyz** [GhostText/GhostText#49]
OMG, this is sooo cool. I love this extension/sublime package.

Is there any way to have this work in codepen on all the textareas eg. HTML, CSS, JS?

P.S. Don't sell this to codepen :)

**Comment by Cacodaimon** [comment]
Thanks, @bfred-it had a Idea about this topic: https://github.com/Cacodaimon/GhostText-for-Chrome/issues/34 maybe we find the time for this feature soon.

**Comment by AJeezy9** [comment]
+1 for this functionality. Would make my life easier in more than a few of my daily activities.

**Comment by frdmn** [comment]
+1

**Comment by bfred-it** [comment]
Try this out! https://github.com/GhostText/GhostText/pull/122
