### ISSUE TITLE
Ghosttext fills the Chrome developer console with "Array[2]"

### ISSUE THREAD

**Issue by looeee** [GhostText/GhostText#52]
I'm using Sublime Text 3 and Codepen, and its seems for every line that gets updated in Codepen one line of "Array[2]" gets added, so my console quickly ends up looking like this, which is rather annoying as I want to use it to debug my code:

VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]
VM193:1 Array[2]

**Comment by Cacodaimon** [comment]
Thank you for your help, I "moved" the issue here: https://github.com/Cacodaimon/GhostText-for-Chrome/issues/48
