### ISSUE TITLE
Wordpress 4.4.2 opens 3 tabs in Sublime 3

### ISSUE THREAD

**Issue by smlombardi** [GhostText/GhostText#57]
I am working on a Wordpress 4.4.2 site with Chrome Version 51.0.2662.0 canary (64-bit).
Sublime 3, build 3107
Mac OS 11.4

I choose the command Shift-command-k and sublime loads **3 tabs** with my text in it.

**Comment by Cacodaimon** [comment]
Yeah I can reproduce this behavior, really strange.

**Comment by bfred-it** [comment]
I think this is the same as #95. Unrelated to WordPress.
