### ISSUE TITLE
Doesn't open Sublime Text

### ISSUE THREAD

**Issue by revolter** [GhostText/GhostText#63]
For some reason, it doesn't work on the mac at work. I click the Chrome Add-on button, it asks me to select the desired text area, and after clicking it, the "There are multiple ..." popup remains open and it does nothing. No error in the Chrome or Sublime Text console.

**Comment by bfred-it** [comment]
What site is that happening on? Does it work on this page?

**Comment by revolter** [comment]
Any site. No, it doesn't work here. I'm also on OS X 10.10.5.

I'm getting these in the console:

	GhostText: There are multiple text areas on this page. 
	  Click on the one you want to use.
	GhostText: detector.focusEvent()
	GhostText: reportFieldData()
	GhostText: detector.focusEvent()
	GhostText: reportFieldData()
	GhostText: detector.focusEvent()
	GhostText: reportFieldData()
	GhostText: detector.focusEvent()
	GhostText: reportFieldData()

And if I open Sublime Text and open the browser again, a red popup appears with the message:

	Connection error. 
	Make sure that Sublime Text is open and has GhostText installed. 
	Try closing and opening it and try again. 
	Make sure that the port matches (4001 is the default). 
	See if there are any errors in Sublime Text's console.

**Comment by bfred-it** [comment]
Thanks! Let's try this:

0. Reinstall GT in Sublime Text
0. Restart Sublime Text 
0. Reopen this tab (to avoid any GT remnants)
0. Click the GT button in Chrome
0. Click on the Reply box
0. Copy what's in the Sublime Text console (possibly all of it, to see if GT server has started correctly)

**Comment by revolter** [comment]
Still nothing shows up in the Sublime Text console __after__ selecting this text area, but I found some interesting logs written on Sublime Text start:

	plugins loaded
	PyV8: Creating new thread
	Emmet: Creating thread
	Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
	Emmet: You have the most recent PyV8 binary
	Package Control: Repository http://sublime.wbond.net/repositories.json does not appear to be a valid repository file because  the "packages" key is an object, not an array. This indicates it is a channel not a repository.
	Package Control: Repository http://sublime.wbond.net/repositories.json does not appear to be a valid repository file because  the "packages" key is an object, not an array. This indicates it is a channel not a repository.
	Package Control: No updated packages
	ignored packages updated to: ["GhostText", "Vintage"]
	reloading Packages/User/Package Control.sublime-settings
	reloading Packages/User/Preferences.sublime-settings
	reloading Packages/User/Package Control.sublime-settings
	ignored packages updated to: ["Vintage"]
	reloading plugin GhostText.FocusSublimeWindow
	reloading plugin GhostText.GhostText
	GhostText is starting now…
	Traceback (most recent call last):
	  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 120, in reload_plugin
	    m.plugin_loaded()
	  File "GhostText in /Users/Iulian/Library/Application Support/Sublime Text 3/Installed Packages/GhostText.sublime-package", line 159, in plugin_loaded
	  File "GhostText in /Users/Iulian/Library/Application Support/Sublime Text 3/Installed Packages/GhostText.sublime-package", line 69, in __init__
	  File "Http.HttpServer in /Users/Iulian/Library/Application Support/Sublime Text 3/Installed Packages/GhostText.sublime-package", line 14, in __init__
	OSError: [Errno 49] Can't assign requested address
	reloading Packages/GhostText/GhostText.sublime-settings
	reloading Packages/User/Package Control.sublime-settings
	reloading Packages/User/Preferences.sublime-settings
	reloading Packages/User/Preferences.sublime-settings

**Comment by bfred-it** [comment]
I think `Can't assign requested address` refers to either a port already in use or a misassignment of `localhost`

Try running this command when Sublime Text is closed:

```sh
lsof -i :4001
```

It shouldn't output anything. If it does stop here and post a screenshot/copy-paste.

Now open it and run it again, GhostText should be using that port and it should look something like this:

<img width="750" alt="Port 4001 used by GhostText-ST" src="https://cloud.githubusercontent.com/assets/1402241/14077806/8085174e-f4a4-11e5-9c82-ef6d76daecb8.png">

Do you have any server running locally? Does `localhost` work correctly there?

**Comment by revolter** [comment]
Uhm, I modified the `hosts` file and `localhost` points to another PC on the network. So this must be the cause. That command doesn't output anything indifferently if Sublime Text is opened or not.

I removed that and the command generated output like yours. But it still doesn't connect. I'll restart Chrome and update this comment.

**Comment by bfred-it** [comment]
Repeat this and let's see what we have now: https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/63#issuecomment-202321121

**Comment by revolter** [comment]
Package Control: Repository http://sublime.wbond.net/repositories.json does not appear to be a valid repository file because  the "packages" key is an object, not an array. This indicates it is a channel not a repository.
	Package Control: No updated packages
	ignored packages updated to: ["GhostText", "Vintage"]
	reloading Packages/User/Package Control.sublime-settings
	reloading Packages/User/Preferences.sublime-settings
	reloading Packages/User/Package Control.sublime-settings
	ignored packages updated to: ["Vintage"]
	reloading plugin GhostText.FocusSublimeWindow
	reloading plugin GhostText.GhostText
	GhostText is starting now…
	Setting on request handler
	reloading Packages/GhostText/GhostText.sublime-settings
	HTTP Start
	reloading Packages/User/Package Control.sublime-settings
	reloading Packages/User/Preferences.sublime-settings
	reloading Packages/User/Preferences.sublime-settings

**Comment by bfred-it** [comment]
Thank you! The server seems to be starting but I'm not sure of where the issue is now. Any new messages in Chrome's console?

**Comment by revolter** [comment]
I attached the Chrome log: [github.com-1459173729368.log.zip](https://github.com/Cacodaimon/GhostText-for-SublimeText/files/191870/github.com-1459173729368.log.zip)

**Comment by revolter** [comment]
It works now, thanks for reminding me about this.

**Comment by bfred-it** [comment]
That's good to hear! I definitely didn't know what was up back then 😅

**Comment by revolter** [comment]
Probably my computer's fault. I changed it since then too.

**Comment by NBR-hugh** [comment]
- the same Question:
    + > For some reason, it doesn't work on the mac at work. I click the Chrome Add-on button, it asks me to select the desired text area, and after clicking it, the "There are multiple ..."

- I don't know which part is wrong.So I have try:
    + X  restart chrome  
    + X  restart ST3
    - O  to connect the same page via firefox,and it work. 
        - Then I return chrome try again ,it works also. 
- I don't know the reason really 
- but post my attempts which may help others

- Chrome Console:

```
GhostText: selectField()
input-area.js:298 TypeError: Cannot read property 'querySelectorAll' of null
    at Detector.addAceElements (input-area.js:252)
    at Detector.detect (input-area.js:195)
    at Detector.addIframes (input-area.js:295)
    at Detector.detect (input-area.js:199)
    at Object.selectField (content.js:160)
    at messageHandler (content.js:49)
    at EventImpl.dispatchToListener (VM23 extensions::event_bindings:403)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (VM23 extensions::event_bindings:387)
    at EventImpl.dispatch (VM23 extensions::event_bindings:409)
```
