### ISSUE TITLE
GhostText not working in a pop-up window

### ISSUE THREAD

**Issue by aajii** [GhostText/GhostText#67]
In a pop-up window (a compose window for a email service) I try to open GhostText with a keyboard shortcut and nothing happens. Nothing showing up in Chrome console either.

Windows 10
Chrome 50.0.2661.94 m
GhostText 1.1.4
Sublime 3 dev build 3112

**Comment by bfred-it** [comment]
@aajii 
0. Go to: `chrome://extensions/`
0. Scroll to the bottom
0. Click on "Keyboard shortcuts" on the bottom right
0. Make sure that there's a shortcut defined

@Cacodaimon it doesn't seem to be working on my computer either, the API doesn't seem to have changed: `_execute_browser_action` on https://developer.chrome.com/extensions/commands
Does it work for you?

**Comment by aajii** [comment]
@bfred-it The shortcut is defined, and it works elsewhere, but this pop-up (without an address bar, plugin buttons, etc.) seems to be an exception.

**Comment by bfred-it** [comment]
v1.2.1 fixed this

https://github.com/GhostText/GhostText/commit/16a1dade6c10168cff320e0968301febc4b42a27

**Comment by AminaG** [comment]
I download it today from Chrome Web Store. still not working
בתאריך 5 בספט׳ 2016 17:32,‏ "Federico Brigante" <notifications@github.com>
כתב:

**Comment by bfred-it** [comment]
You need to re-set the shortcut in the options, it works

**Comment by aajii** [comment]
On 5 September 2016 at 20:18, Federico Brigante <notifications@github.com>
wrote:

> You need to re-set the shortcut in the options, it works
>

I don't know what's wrong with my Chrome but now it's not doing anything
:-(. I tried to reinstall the plugin (in both Chrome and ST3) as well as
reassign the keyboard shortcut. Now I do not get connection between Chrome
and Sublime at all.

a-j

**Comment by bfred-it** [comment]
Sorry, the previous version was broken as per #80 

Try 1.2.2

**Comment by bfred-it** [comment]
Make sure that it works normally first, by clicking the button

**Comment by aajii** [comment]
On 6 September 2016 at 10:18, Federico Brigante <notifications@github.com>
wrote:

> Sorry, the previous version was broken as per #80
> <https://github.com/GhostText/GhostText/issues/80>
>
> Try 1.2.2
>

Yes, now it works, both from the button as well as the keyboard shortcut.

Thanks a million, it really makes my workflow smoother.

a-j
