### ISSUE TITLE
Doesn't work with Wordpress

### ISSUE THREAD

**Issue by elmerehbi** [GhostText/GhostText#68]
I saw the other issue about Wordpress but I am not sure it is the same problem. I wanted to draft a new post and when clicking the GhostText I get the following message:

> There are multiple text areas on this page. Click on the one you want to use.

I tried choosing the title field and the composition field but both return the same message.

**Comment by bfred-it** [comment]
Are you trying in the main Wordpress content field?

**Comment by elmerehbi** [comment]
Yes I did. Does it work for you?

On 04:25, Wed, May 18, 2016 Federico Brigante <notifications@github.com>
wrote:

> Are you trying in the main Wordpress content field?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GhostText/GhostText/issues/68#issuecomment-219908575>
>
-- 
Sincerely Yours,
Ibrahim EL MEREHBI

elmerehbi.com <http://bit.ly/iem_com>

**Comment by bfred-it** [comment]
It does. 

![GT WP screencast](https://cloud.githubusercontent.com/assets/1402241/15356830/03041b92-1cb0-11e6-9984-ae29a8cf4adf.gif)

What OS and browser are you using?

**Comment by elmerehbi** [comment]
Ubuntu & Chrome. Might be due to some other extension?
