### ISSUE TITLE
VS Code Support

### ISSUE THREAD

**Issue by tracker1** [GhostText/GhostText#74]
Would be nice to see a plugin/extension for VS Code.

**Comment by bfred-it** [comment]
This is unlikely to happen unless someone steps in. GT is currently in maintenance-only

**Comment by jtokoph** [comment]
I've added GhostText support to Visual Studio Code.

Marketplace page: https://marketplace.visualstudio.com/items?itemName=tokoph.ghosttext
Github Repository: https://github.com/jtokoph/ghosttext-vscode

**Comment by bfred-it** [comment]
Nice!! Is it possible to auto-start the server?

_Sent from my VS Code editor_

**Comment by jtokoph** [comment]
It is possible. I was just following what was being done in Atom. I think VSCode operates in the same way as Atom in that every extension gets loaded once per window. Not sure how it should behave with autostart.

**Comment by bfred-it** [comment]
No problem! As long as it's clear in the readme like it is :D

**Comment by bfred-it** [comment]
Added to the readme: https://github.com/GhostText/GhostText#installation
