### ISSUE TITLE
Doesn't work on fields inside iframes

### ISSUE THREAD

**Issue by lsloan** [GhostText/GhostText#75]
GhostText for Chrome doesn't recognize textarea elements shown in the result pane of JSFiddle pages.  For example, I've made this very simple JSFiddle that contains HTML which makes a form with a textarea element, no JavaScript, and no CSS:

https://jsfiddle.net/lsloan/1a2nywf0/

Even when the textarea element in the results pane already has focus, activating GhostText on that page shows the message:

> There are multiple text areas on this page.  Click on the one you want to use.

GT only acknowledges clicks on the textarea elements associated with the other panes for HTML, JavaScript, or CSS.  Nothing happens when the textarea element in the result pane is clicked.

A similar thing happens when viewing the embedded version of this JSFiddle, showing only the result tab:

https://jsfiddle.net/lsloan/1a2nywf0/embedded/result/

Whether the textarea element has focus, activating GT shows this message (in red):

> No text area elements on this page

I have several extensions installed in Chrome.  However, I successfully reproduced the same problem in a new profile that had only the GT extension installed.

I'm using:
- Google Chrome Version 51.0.2704.84 (64-bit)
- GhostText for Chrome 1.1.4
- "Ghost Text for VIm" - https://github.com/falstro/ghost-text-vim
  - Which required an upgrade to Tcl/Tk 8.6.4, installed using homebrew
- MacVim Custom Version 7.4 (81)

Note that the interface with Vim works well enough and doesn't seem to be the problem in this case.  I've been successful in getting GT to open Vim documents with the contents of textarea elements on other web pages.

**Comment by bfred-it** [comment]
Thanks for the detailed report. This is a known issue, **GT doesn't look for text boxes inside iframes** at this moment

**Comment by sloanlance** [comment]
Sorry for the dupe. If you'd like to reference this issue from the other and close this issue, I won't mind.

**Comment by bfred-it** [comment]
Try this out! https://github.com/GhostText/GhostText/pull/122
