### ISSUE TITLE
Content not loaded on Vivaldi

### ISSUE THREAD

**Issue by thotty** [GhostText/GhostText#77]
A catch one error on execute on Vivaldi (Chromium based browser)...
On `scripts/lib.js:65`

``` javascript
if (hasContentJs[0]) {
//...
}
```

The var `hasContentJs` is not a `Array`

Someone catch too?

**Comment by bfred-it** [comment]
Apparently vivaldi doesn't support the parameter [`code`](https://developer.chrome.com/extensions/tabs#method-executeScript), which we use to [detect whether the script has been already injected](https://github.com/GhostText/GhostText/blob/master/browser/scripts/lib.js#L63) into the page. Unless you know of any other way to do that, we can't add compatibility.

**Comment by AminaG** [comment]
I fixed it in pull request #83

**Comment by bfred-it** [comment]
I just tested this in Vivaldi 1.7.735.46 and they fixed it ^__^
