### ISSUE TITLE
Could not load in APP mode

### ISSUE THREAD

**Issue by AminaG** [GhostText/GhostText#79]
I am using Chrome in app mode (full window) by running a page using `add to desktop` feature.

![image](https://cloud.githubusercontent.com/assets/3584317/18245555/865b980c-736e-11e6-852e-b2b828ea74df.png)

Then I try to run the extension using the command (alt+shift+k) or (alt+ctrl+k). But it is not working. Nothing happend. I think it is not working, because there is no extension toolbar in Chrome desktop mode.

The easiest way to solve it is by using [chrome api commands](https://developer.chrome.com/extensions/commands), and execute it by command/

@bfred-it Can you add it please?

Thank you!

**Comment by bfred-it** [comment]
v1.2.1 fixed this

https://github.com/GhostText/GhostText/commit/16a1dade6c10168cff320e0968301febc4b42a27
