### ISSUE TITLE
ReferenceError: GhostText is not defined

### ISSUE THREAD

**Issue by mike2410** [GhostText/GhostText#80]
I'm using Chrome Version 53.0.2785.89 m, with the GhostText Extension for chrome 1.2.1 and the Sublime Text 3 package GhostText 1.0.13, running on Windows 7 Professional x64.

Whenever I try to activate GhostText the chrome console produces the following output:
`Got message: Object {action: "select-field", tabId: 38}`
`GhostText: selectField()`

followed by this error:
`Error in event handler for runtime.onMessage: ReferenceError: GhostText is not defined`

Sublime Text itself seems to be able to successfully start GhostText, however does not seem to log anything thereafter.

Any help would be very much appreciated,
cheers.

**Comment by ljspace** [comment]
The same problem

**Comment by AminaG** [comment]
I think it related to  the last update. #81

**Comment by bfred-it** [comment]
Sorry about this, I'm looking into it.

**Comment by bfred-it** [comment]
1.2.2 should work

**Comment by AminaG** [comment]
Thank you for uploading new version to Chrome Web Store.
For make it ASAP for everyone
- Navigate to: `chrome://extensions`
- click on `Developer mode`
- click `Update extensions now`

![image](https://cloud.githubusercontent.com/assets/3584317/18264986/069e2e14-741c-11e6-905c-4ebfb3a55560.png)
