### ISSUE TITLE
No tab is open when using the Firefox plugin

### ISSUE THREAD

**Issue by gwenzek** [GhostText/GhostText#86]
I'm using Ghost Text with both Chrome and Firefox.

It works fine with Chrome but not with Firefox.
No tab is opened in ST, making it impossible to type text.

Here is the console output:

```
// Launch GhostText from Chrome
WebSocketServer id: 3
Setting on message handler
Setting on close handler
Start
Listening on: 40649
Bind view with id: 50
Setting on message handler
// Launch GhostText from Firefox
WebSocketServer id: 4
Setting on message handler
Setting on close handler
Start
Listening on: 38185
```

As you can see for some reason ST starts listening GhostText but doesn't open a view.

**Comment by bfred-it** [comment]
Are you using what's on the addons.mozilla.oth website or the version on this repo? The AMO version is deprecated.

**Comment by gwenzek** [comment]
I'm using [the link from the README](https://addons.mozilla.org/firefox/addon/ghosttext-for-firefox/)
Where is this repo's version ?

I also tried to follow the [second README](https://github.com/GhostText/GhostText/tree/master/browser) without success (nothing happening on both side)

**Comment by bfred-it** [comment]
That's the right version.

After following the instructions:
- Does the extension appear in the list?
- Does the button appear there?
- If it does, are you testing here on github?

**Comment by gwenzek** [comment]
Thanks I managed to install it.
The thing which is confusing is that the version on the addons.mozilla.org is not working.
Can't someone release a more recent version ?
Anyway it should be mentionned in the main README.

I followed the instruction inside the development version
[README](https://github.com/GhostText/GhostText/tree/master/browser).

The `npm run build` failed because I was on Ubuntu with the wrong version of
node-js installed. This is a known issue described
[here](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu#21171188).

After `sudo apt-get install nodejs-legacy`, I was able to build the plugin
and it's working !

Note that even if the `npm run build` fail, you can still add the plugin to Firefox
and it will show the button but it will be non-working.

**Comment by bfred-it** [comment]
Is it working or non-working? What happens when you click the button while you're on this page?

**Comment by gwenzek** [comment]
Sorry if I haven't been clear but it's working normally now. Clicking on the button ask to select a text area and then a tab is open in ST.

I detailed the install instructions and problem I faced on case someone has the same problem than me.

**Comment by bfred-it** [comment]
Cool, thanks for the report! Unfortunately I can't update the plugin on addons.mozilla

**Comment by bfred-it** [comment]
The new GhostText Firefox extension has been published https://addons.mozilla.org/en-US/firefox/addon/ghosttext/ :)

**Comment by gwenzek** [comment]
Thanks for the update ! The official Firefox plugin is working smoothly now :-)

**Comment by bfred-it** [comment]
Good to hear :)
