### ISSUE TITLE
[Bug] Not connection

### ISSUE THREAD

**Issue by Kristinita** [GhostText/GhostText#88]
### Summary

I can not begin to use GhostText.

### Expected behavior

<https://www.youtube.com/watch?v=e0aLFPtYPZI&feature=share>

### Actual behavior

No connection. If I wrote my text in Sublime Text, I can not see text in textarea fields in browser.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text, Firefox and Chrome without plugins and user settings.

I install Firefox addon and Sublime Text package. I install `nircmd` files in `C:\Windows` and `C:\Windows\nircmd` folders. I restart Sublime Text and Firefox.

I install `MarkdownEditing` plugin, I select `MarkdownGFM` syntax:

```python
>>> view.settings().get('syntax')
'Packages/MarkdownEditing/Markdown.tmLanguage'
```

Sublime console output, when I start Sublime Text:

    reloading plugin GhostText.FocusSublimeWindow
    reloading plugin GhostText.GhostText
    GhostText is starting now…
    Setting on request handler

I press Ghost button in Firefox page with `textarea` element, `textarea` element now have blue border for me:

![Blue border](http://i.imgur.com/X7280dR.png)

Sublime Text window now active for me. Sublime Text console output:

    WebSocketServer id: 1
    Setting on message handler
    Setting on close handler
    Start
    Listening on: 55603

But if I wrote text in my Sublime Text markdown file, text not print in Firefox textarea field.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126
**Firefox:**
49.0.2
**nircmd:**
2.81
**GhostText for Firefox:**
0.0.10.1-signed.1-signed

Thanks.

**Comment by bfred-it** [comment]
Thanks for the detailed bug report!

That version is deprecated, install it via: https://github.com/GhostText/GhostText/tree/master/browser#on-firefox

**Comment by Kristinita** [comment]
I'm sorry, this solution not solved my problem.

1. If I install new addon as `Load Temporary Add-on` addon was removed in next Firefox seance. I don't want download GhostText each time, when I want to use GhostText.
2. Solution not worked for me. If I press Ghost Button, I not get blue border in `textarea` element and I can not output in Sublime Text console. Firebug output:

![Firebug output](http://i.imgur.com/FqRDLjP.png)

    Got message: Object { action="select-field",  tabId=1}
    content.js (line 39)
    <system>

    GhostText: selectField()
    content.js (line 150)
    <system>

Thanks.

**Comment by bfred-it** [comment]
1. Unfortunately I can't do anything about since my collaborator @Cacodaimon hasn't updated the extension on Mozilla's site
2. Does it work here on GitHub? You should be seeing this **when you click on the textarea**

<img width="903" alt="test" src="https://cloud.githubusercontent.com/assets/1402241/19937414/669c9816-a0de-11e6-9dbc-a1444539ee1f.png">

**Comment by Kristinita** [comment]
GhostText not worked in GitHub for me. Actual behavior for me:

![Actual behavior](http://i.imgur.com/vdNzRiU.png)

May you say step-by-step actions for your behavior? 

Thanks.

**Comment by bfred-it** [comment]
0. Open Sublime Text with GhostText installed
0. Open https://github.com/GhostText/GhostText/issues/88
0. Click on GhostText's button
0. See this message  
<img width="413" alt="There are multiple textarea elements on this page. Click on the one you want to use." src="https://cloud.githubusercontent.com/assets/1402241/19956381/30e83aca-a149-11e6-9322-c3fa5942fd13.png">
0. Click on the reply `textarea`  
<img width="780" alt="reply textarea" src="https://cloud.githubusercontent.com/assets/1402241/19956385/4264be72-a149-11e6-8396-ce51ca6553f6.png">
0. See this message  
<img width="409" alt="Connected! You can switch to your editor." src="https://cloud.githubusercontent.com/assets/1402241/19956404/6d23cc48-a149-11e6-9b11-26def5e4f01a.png">
0. See the `textarea` turn blue
<img width="762" alt="connected reply textarea" src="https://cloud.githubusercontent.com/assets/1402241/19956396/5a95b942-a149-11e6-9eb0-51d199c78f1c.png">

**Comment by Kristinita** [comment]
Thank you very much! Now is worked for me.

![GhostText](https://psv4.vk.me/c810324/u2000033196/docs/5950c5662440/file.gif?extra=OCPEyiZhUBZvEM3gA-4njNP2ZwFacDlCTGM6cr7zpeMkyzONsOinrC3J-Qfov9ZDukX0qsLHfrXq2n4hm62oC0mNT3c8ZCNAVK-mCRCTxZYftyUQUK7hx91_)

But I still have problem 1. GhostText addon for Firefox was removed if I restart Firefox. [I don't have answer in Super User](http://superuser.com/questions/1141922/installing-firefox-addon-forever-as-load-temporary-add-on). Any ideas? I think, it is critical problem and you may lose many Firefox users.

Thanks.

**Comment by bfred-it** [comment]
👍 

Yeah unfortunately there's nothing I can do. I can't publish a new version of GhostText to Mozilla Addons :(

**Comment by Kristinita** [comment]
@bfred-it , I asked in [MozillaZine](http://forums.mozillazine.org/viewtopic.php?f=27&t=3025064&e=0) and [Super User](http://superuser.com/q/1141922/572069), but I have not success. I unsuccessfully write to @Cacodaimon. Any ideas?

And why issue is closed? Firefox problem is not solved.

Thanks.

**Comment by bfred-it** [comment]
Issue closed because Cacodaimon is already aware of the problem and thus is is a duplicate of https://github.com/GhostText/GhostText/issues/70
