### ISSUE TITLE
[Feature request] "nircmd path" option

### ISSUE THREAD

**Issue by Kristinita** [GhostText/GhostText#89]
### Request

Add `"nircmd path"` option for Sublime Text package, so users can custom path to a file `nircmd.exe`.

### Justification

I download nircmd use [Chocolatey](https://chocolatey.org/). This is useful for several reasons.

1. Quick download: I need only print `cinst nircmd -y` in terminal.
2. If I reinstall Windows, I can quick reinstall all my programs.
3. I can quick update all my Chocolatey programs only use command `cup all -y`.

But my Chocolatey path for nircmd is `E:\Chocolatey\lib\nircmd\tools`, not `C:\Windows`.

### Extended behavior

In Sublime Text `Preferences` → `Package Settings` → `Ghost Text` → `Settings - User` → I can add `"nircmd_path": "E:\Chocolatey\lib\nircmd\tools"` option.

Thanks.

**Comment by bfred-it** [comment]
GT does not look for files specifically in `C:\Windows` but it just expects Windows to know where to find that file. Usually this is done via the global PATH, which is essentially a list of directories the shell looks into to find executables.

For Chocolatey, have a look at this: https://github.com/chocolatey/choco/wiki/FeaturesShim or https://www.java.com/en/download/help/path.xml
