### ISSUE TITLE
How to activate GhostText in sublime on a mac? 

### ISSUE THREAD

**Issue by cwildenb** [GhostText/GhostText#90]
I've downloaded the sublime text editor and also the ghosttext extension on google chrome. I've entered a code into a text box on facebook, and clicked the ghost icon on chrome. It opens up sublime, and tells me it has been connected. I then go into the sublime text editor and when I had a code in the browser, it didn't show up in the editor. I also tried with an empty text box in the google chrome browser and it would ask me the multiple text area prompt and i'd select one and it highlights the text box in blue and opens sublime. But when I'd type in sublime, it wasn't showing in the browser. I have put the ghosttext zip from github into the package folder in sublime. I wonder why I am getting this issue. Oh, I'm also doing this on a mac OS X. Please let me know.

**Comment by bfred-it** [comment]
I also use OS X. What version of Chrome, OS X and Sublime are you using?

**Comment by cwildenb** [comment]
Sublime Build 3126, Google Chrome Version 54.0.2840.71 (64-bit), OS X El Capitan Version 10.11.6

**Comment by cwildenb** [comment]
Got it to work! Thanks
