### ISSUE TITLE
The Mutation Events option has been discontinued. Alternatively, use the MutationObserver.

### ISSUE THREAD

**Issue by joniEAHH** [GhostText/GhostText#91]
Hi,

When I try to run the module on firefox it gives me this error on input-area.js
The Mutation Events option has been discontinued. Alternatively, use the MutationObserver.

The line from error is:
this.textArea.addEventListener('DOMNodeRemovedFromDocument', this.elementRemovedListener, false);

Thanks in advance.
[input-area.zip](https://github.com/GhostText/GhostText/files/632030/input-area.zip)

**Comment by bfred-it** [comment]
It's not an error but a warning, it still works. Feel free to send a PR to implement this https://stackoverflow.com/questions/31798816/simple-mutationobserver-version-of-domnoderemovedfromdocument
