### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by daniloprates** [GhostText/GhostText#92]
I have all set, but it simply doesn't work. Already reopened both chrome and st3.

The ST console doesn't output anything.

![screen shot 2016-12-16 at 16 08 27 2](https://cloud.githubusercontent.com/assets/1504716/21273305/120f4322-c3aa-11e6-9f72-26a5b2b6d4b3.png)

**Comment by mydiva** [comment]
I am facing the same issue.

**Comment by bfred-it** [comment]
Does this work after a restart?
