### ISSUE TITLE
Not connection sometimes

### ISSUE THREAD

**Issue by Kristinita** [GhostText/GhostText#96]
### 1. Summary

Sometimes (4 or 5 times) I can not use GhostText. I select `textarea` element, but GhostText and Sublime Text not connected.

### 2. Expected behavior

Successfully connecting always.

### 3. Actual behavior

I saw blue border around selected `textarea` element, but I don't get connection

![Actual](http://i.imgur.com/pyJkIFg.png)

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text and Firefox without plugins and user settings.

I run Firefox → I run Sublime Text → I create new issue in your repository in browser → I click to GhostText button in browser → I select `textarea` element → I get actual behavior.

Only Windows restart solve my problem.

### 5. Not helped

1. I don't see output in Sublime Text console and in [**Firebug**](https://addons.mozilla.org/ru/firefox/addon/firebug/).
2. I restart Sublime Text and Firefox — no effect.
3. I don't find unexpected processes in [**ProcessHacker**](http://processhacker.sourceforge.net/).

### 6. Feature Request

It would be nice, if you add `debug` setting, that could be possible to determine the cause of the connection lack.

### 7. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Firefox:**
51.0.1 (64-bit)
**GhostText for Firefox:**
1.2.4.1
**GhostText for Sublime Text:**
1.0.13

Thanks.

**Comment by bfred-it** [comment]
When this happens again, can you try connecting with Chrome?
