### ISSUE TITLE
TypeError: ghostTextCodeMirrorEditor.blur is not a function

### ISSUE THREAD

**Issue by Eeems** [GhostText/GhostText#98]
When attempting to use this addon in Firefox nightly on windows 10, I'm getting the following errors:
![Screenshot](http://i.imgur.com/ZylLwCg.png)

**Comment by bfred-it** [comment]
Thanks for the report! It does however keep working in my tests

**Comment by Eeems** [comment]
@bfred-it Are you testing in Firefox Nightly or stable?

**Comment by bfred-it** [comment]
The error should no longer appear
